### ISSUE TITLE
Review logging

### ISSUE THREAD

**Issue by smtakeda** [snowflakedb/libsnowflakeclient#7] opened 2018-01-30 01:09 UTC
Goals

- Ensure the log includes required info for debug.
- Ensure the log can be enabled and disabled as the customer needs.
- Ensure the log location can be specified.
- Ensure the log doesn't include sensitive information, i.e., password, private key

**Comment by smtakeda** [comment] 2018-02-10 18:57
Questions:
- How DEBUG global flag is used aside from multiple log level?
- Can we set the log directory or even file for log after snowflake_global_init?

**Comment by howryu** [comment] 2018-02-11 01:55
Another question to think about is how to provide interface to hook logging facilities to upper layer, i.e. ODBC

**Comment by bdforbes** [comment] 2020-12-04 06:46
Hi, I'm wondering if this issue is the root cause of something I've encountered in the Snowflake ODBC driver (version 2.20.05.00). I've set up a 64-bit ODBC Data Source connection in Windows, specifying a Tracing level of 0. However, when I use the ODBC connection from R, I still see a huge amount of logging going to the console (I think it's stderr). It's almost entirely INFO level tracing about the connection, which I though should be excluded with Tracing set to 0.

![image](https://user-images.githubusercontent.com/15697539/101130948-887f5400-3658-11eb-95e9-86dd7d1b1a9f.png)

Is this a known issue?

**Comment by sfc-gh-igarish** [comment] 2023-03-11 00:39
To clean up and re-prioritize more pressing bugs and feature requests we are closing all issues older than 6 months as of March 1, 2023. If there are any issues or feature requests that you would like us to address, please create them according to the new templates we have created. For urgent issues, opening a support case with this link [Snowflake Community](https://community.snowflake.com/s/article/How-To-Submit-a-Support-Case-in-Snowflake-Lodge) is the fastest way to get a response.

**Closed by sfc-gh-igarish** 2023-03-11 00:39 UTC
